version: '3.8'

services:
  app:
    build: .
    container_name: booking_service_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - "./.env"
    command: >
      sh -c "alembic upgrade head && fastapi dev app/main.py --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: booking_service_db
    env_file:
      - "./.env"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: